/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import com.devazt.networking.HttpClient;
import com.devazt.networking.OnHttpRequestComplete;
import com.devazt.networking.Response;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;
/**
 *
 * @author marij
 */
public class ActInv extends javax.swing.JFrame {

    int estado;
    String Nombre, Cantidad;
    
    public ActInv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnOk = new javax.swing.JButton();
        TfCant = new javax.swing.JTextField();
        LbCant = new javax.swing.JLabel();
        TfIdProd = new javax.swing.JTextField();
        LbNomPro = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        LbCantidad = new javax.swing.JLabel();
        TfNombre = new javax.swing.JTextField();
        TfCantidad = new javax.swing.JTextField();
        LbAviso = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        LbFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mregresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnOk.setText("Aceptar");
        BtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));
        getContentPane().add(TfCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 210, -1));

        LbCant.setText("Cantidad a ingresar del producto:");
        getContentPane().add(LbCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        TfIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfIdProdActionPerformed(evt);
            }
        });
        getContentPane().add(TfIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 210, -1));

        LbNomPro.setText("Id del producto:");
        getContentPane().add(LbNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        LbNombre.setText("Nombre del producto:");
        getContentPane().add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        LbCantidad.setText("Cantidad actual del producto:");
        getContentPane().add(LbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        TfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(TfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 300, -1));
        getContentPane().add(TfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 300, -1));

        LbAviso.setText("Datos del producto");
        getContentPane().add(LbAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        BtnBuscar.setText("Buscar Producto");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        LbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        LbFondo.setText("jLabel1");
        getContentPane().add(LbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 340));

        Mregresar.setText("Regresar");
        Mregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MregresarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mregresar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MregresarMouseClicked
        MenuExa ventanaMenu= new MenuExa();
        ventanaMenu.estado=this.estado;
        if(estado == 1){
            ventanaMenu.nivel1();
        }
        else if (estado == 2){
            ventanaMenu.nivel2();
        }
        else if (estado ==3 ){
            ventanaMenu.nivel3();
        }
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MregresarMouseClicked

    private void TfIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfIdProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfIdProdActionPerformed

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
        HttpClient cliente = new HttpClient(new OnHttpRequestComplete() {
            @Override
            public void onComplete(Response status) {
                // Este método se llama cuando la solicitud HTTP se completa
                if (status.isSuccess()) {
                    JOptionPane.showMessageDialog(null, "Éxito, se guardó correctamente en la Base de datos.");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar en la Base de datos. ");
                }
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });

        String IdProd = TfIdProd.getText().toString();
        String Cantidad = TfCant.getText().toString();

        cliente.excecute("http://localhost/Api/Exa_ActInv_Actu.php?Id_Prod=" + IdProd + "&Cantidad=" + Cantidad + "");
    }//GEN-LAST:event_BtnOkActionPerformed

    private void TfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNombreActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        HttpClient cliente = new HttpClient(new OnHttpRequestComplete() {
            @Override
            public void onComplete(Response status) {

                try {
                    JSONObject producto = new JSONObject(status.getResult());
                    String nombreWeb = producto.getJSONObject("0").get("Nombre").toString();
                    String cantidadWeb = producto.getJSONObject("0").get("Cantidad").toString();
                    if (nombreWeb != null && cantidadWeb != null) {
                        TfNombre.setText(nombreWeb);
                        TfCantidad.setText(cantidadWeb);
                    } else {
                        JOptionPane.showMessageDialog(null, "No hay en existencia el producto en la base de datos. ");
                    }

                } catch (Exception e) {
                }
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });

        String IdProd = TfIdProd.getText().toString();
        cliente.excecute("http://localhost/Api/Exa_ActInv_Buscar.php?Id_Prod=" + IdProd + "");
    }//GEN-LAST:event_BtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActInv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnOk;
    private javax.swing.JLabel LbAviso;
    private javax.swing.JLabel LbCant;
    private javax.swing.JLabel LbCantidad;
    private javax.swing.JLabel LbFondo;
    private javax.swing.JLabel LbNomPro;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JMenu Mregresar;
    private javax.swing.JTextField TfCant;
    private javax.swing.JTextField TfCantidad;
    private javax.swing.JTextField TfIdProd;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
