/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author marij
 */
public class ActInv extends javax.swing.JFrame {

    /**
     * Creates new form ActInv
     */
    public ActInv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnOk = new javax.swing.JButton();
        LbCant = new javax.swing.JLabel();
        TfCant = new javax.swing.JTextField();
        TfIdProd = new javax.swing.JTextField();
        LbNomPro = new javax.swing.JLabel();
        LbAviso = new javax.swing.JLabel();
        LbFondo = new javax.swing.JLabel();
        LbFechaComp1 = new javax.swing.JLabel();
        TfFecha1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mregresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnOk.setText("Aceptar");
        BtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        LbCant.setText("Cantidad del producto:");
        getContentPane().add(LbCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        getContentPane().add(TfCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 410, -1));

        TfIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfIdProdActionPerformed(evt);
            }
        });
        getContentPane().add(TfIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 410, -1));

        LbNomPro.setText("Id del producto:");
        getContentPane().add(LbNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        LbAviso.setText("Debe de registrar el producto primero.");
        getContentPane().add(LbAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        LbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        LbFondo.setText("jLabel1");
        getContentPane().add(LbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 340));

        LbFechaComp1.setText("Fecha de compra:");
        getContentPane().add(LbFechaComp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        getContentPane().add(TfFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 410, -1));

        Mregresar.setText("Regresar");
        Mregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MregresarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mregresar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MregresarMouseClicked
        MenuExa ventanaMenu= new MenuExa();
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MregresarMouseClicked

    private void TfIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfIdProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfIdProdActionPerformed

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActInv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk;
    private javax.swing.JLabel LbAviso;
    private javax.swing.JLabel LbCant;
    private javax.swing.JLabel LbFechaComp1;
    private javax.swing.JLabel LbFondo;
    private javax.swing.JLabel LbNomPro;
    private javax.swing.JMenu Mregresar;
    private javax.swing.JTextField TfCant;
    private javax.swing.JTextField TfFecha1;
    private javax.swing.JTextField TfIdProd;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
