/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import com.devazt.networking.HttpClient;
import com.devazt.networking.OnHttpRequestComplete;
import com.devazt.networking.Response;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;
/**
 *
 * @author marij
 */
public class MasUser extends javax.swing.JFrame {

    int estado;
    
    public MasUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnOk = new javax.swing.JButton();
        LbId = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        LbPassword = new javax.swing.JLabel();
        TfId = new javax.swing.JTextField();
        TfNombre = new javax.swing.JTextField();
        TfPassword = new javax.swing.JTextField();
        LbNivel = new javax.swing.JLabel();
        TfNivel = new javax.swing.JTextField();
        LbMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnOk.setText("Aceptar");
        BtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        LbId.setText("Id de Usuario:");
        getContentPane().add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        LbNombre.setText("Nombre del nuevo usuario:");
        getContentPane().add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        LbPassword.setText("Contraseña del nuevo usuario:");
        getContentPane().add(LbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        TfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfIdActionPerformed(evt);
            }
        });
        getContentPane().add(TfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 140, -1));
        getContentPane().add(TfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 390, -1));
        getContentPane().add(TfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 370, -1));

        LbNivel.setText("Nivel del permiso del usuario:");
        getContentPane().add(LbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        getContentPane().add(TfNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 270, -1));

        LbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        getContentPane().add(LbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 620, 310));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegresarMouseClicked(evt);
            }
        });
        jMenuBar1.add(BtnRegresar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
        HttpClient cliente = new HttpClient(new OnHttpRequestComplete() {
            @Override
            public void onComplete(Response status) {
                // Este método se llama cuando la solicitud HTTP se completa
                if (status.isSuccess()) {
                    JOptionPane.showMessageDialog(null, "Éxito, se guardó correctamente en la Base de datos.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar en la Base de datos. ");
                }
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
        
        
        String Id_User = TfId.getText().toString();
        String NameUser = TfNombre.getText().toString();
        String Password = TfPassword.getText().toString();
        String nivel = TfNivel.getText().toString();

        cliente.excecute("http://localhost/Api/Exa_MasUser.php?Id_User="+Id_User+"&NameUser="+NameUser+"&Contraseña="+Password+"&estado="+nivel+"");
    }//GEN-LAST:event_BtnOkActionPerformed

    private void TfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfIdActionPerformed

    private void BtnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegresarMouseClicked
        MenuExa ventanaMenu= new MenuExa();
        ventanaMenu.estado=this.estado;
        if(estado == 1){
            ventanaMenu.nivel1();
        }
        else if (estado == 2){
            ventanaMenu.nivel2();
        }
        else if (estado ==3 ){
            ventanaMenu.nivel3();
        }
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk;
    private javax.swing.JMenu BtnRegresar;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbMenu;
    private javax.swing.JLabel LbNivel;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel LbPassword;
    private javax.swing.JTextField TfId;
    private javax.swing.JTextField TfNivel;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JTextField TfPassword;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
