/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import com.devazt.networking.HttpClient;
import com.devazt.networking.OnHttpRequestComplete;
import com.devazt.networking.Response;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;
/**
 *
 * @author marij
 */
public class MenosUser extends javax.swing.JFrame {

    int estado;
    
    public MenosUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbId = new javax.swing.JLabel();
        TfId = new javax.swing.JTextField();
        LbNombre = new javax.swing.JLabel();
        LbNivel = new javax.swing.JLabel();
        LbNomEli = new javax.swing.JLabel();
        LbNivelEli = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        LbMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbId.setText("Id del usuario a buscar");
        getContentPane().add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));
        getContentPane().add(TfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 240, -1));

        LbNombre.setText("Nombre del usuario:");
        getContentPane().add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        LbNivel.setText("Nivel del usuario:");
        getContentPane().add(LbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        LbNomEli.setText("                      ");
        getContentPane().add(LbNomEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 260, -1));

        LbNivelEli.setText("                                                  ");
        getContentPane().add(LbNivelEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        BtnBuscar.setText("Buscar usuario");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        LbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        getContentPane().add(LbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 570, 280));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegresarMouseClicked(evt);
            }
        });
        jMenuBar1.add(BtnRegresar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegresarMouseClicked
        MenuExa ventanaMenu= new MenuExa();
        ventanaMenu.estado=this.estado;
        if(estado == 1){
            ventanaMenu.nivel1();
        }
        else if (estado == 2){
            ventanaMenu.nivel2();
        }
        else if (estado ==3 ){
            ventanaMenu.nivel3();
        }
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarMouseClicked

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        HttpClient cliente = new HttpClient(new OnHttpRequestComplete() {
            @Override
            public void onComplete(Response status) {

                try {
                    JSONObject producto = new JSONObject(status.getResult());
                    String NameUserEli = producto.getJSONObject("0").get("NameUser").toString();
                    String NivelEli = producto.getJSONObject("0").get("estado").toString();
                    if (NameUserEli != null && NivelEli != null) {
                        LbNomEli.setText(NameUserEli);
                        LbNivelEli.setText(NivelEli);
                    } else {
                        JOptionPane.showMessageDialog(null, "El usuario que desea eliminar no existe. ");
                    }

                } catch (Exception e) {
                }
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });

        String IdUser = TfId.getText().toString();
        cliente.excecute("http://localhost/Api/Exa_MenosUser_Buscar.php?Id_User=" + IdUser + "");
    }//GEN-LAST:event_BtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenosUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JMenu BtnRegresar;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbMenu;
    private javax.swing.JLabel LbNivel;
    private javax.swing.JLabel LbNivelEli;
    private javax.swing.JLabel LbNomEli;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JTextField TfId;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
