/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author marij
 */
public class MenosUser extends javax.swing.JFrame {

    /**
     * Creates new form MenosUser
     */
    public MenosUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbId = new javax.swing.JLabel();
        BtnOk = new javax.swing.JButton();
        TfId = new javax.swing.JTextField();
        LbNombre = new javax.swing.JLabel();
        LbNivel = new javax.swing.JLabel();
        LbNomEli = new javax.swing.JLabel();
        LbNivelEli = new javax.swing.JLabel();
        LbMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbId.setText("Id del usuario a Eliminar");
        getContentPane().add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        BtnOk.setText("Eliminar");
        BtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));
        getContentPane().add(TfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 240, -1));

        LbNombre.setText("Nombre del usuario:");
        getContentPane().add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        LbNivel.setText("Nivel del usuario:");
        getContentPane().add(LbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        LbNomEli.setText("                      ");
        getContentPane().add(LbNomEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 260, -1));

        LbNivelEli.setText("                                                  ");
        getContentPane().add(LbNivelEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        LbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        getContentPane().add(LbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 570, 280));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegresarMouseClicked(evt);
            }
        });
        jMenuBar1.add(BtnRegresar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOkActionPerformed

    private void BtnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegresarMouseClicked
        MenuExa ventanaMenu= new MenuExa();
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenosUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenosUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk;
    private javax.swing.JMenu BtnRegresar;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbMenu;
    private javax.swing.JLabel LbNivel;
    private javax.swing.JLabel LbNivelEli;
    private javax.swing.JLabel LbNomEli;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JTextField TfId;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
