/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author marij
 */
public class MenuExa extends javax.swing.JFrame {

    /**
     * Creates new form MenuExa
     */
    public MenuExa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MRegProd = new javax.swing.JMenu();
        MActInv = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MenuMasUser = new javax.swing.JMenu();
        MenuMenosUser = new javax.swing.JMenu();
        MVenProd = new javax.swing.JMenu();
        MSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 390));

        MRegProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Añadir2.png"))); // NOI18N
        MRegProd.setText("Registro de Producto");
        MRegProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MRegProdMouseClicked(evt);
            }
        });
        jMenuBar1.add(MRegProd);

        MActInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reload2.png"))); // NOI18N
        MActInv.setText("Actualizacion de Inventario   ");
        MActInv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MActInvMouseClicked(evt);
            }
        });
        jMenuBar1.add(MActInv);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User2.png"))); // NOI18N
        jMenu2.setText("Administrar Usuarios   ");

        MenuMasUser.setText("Añadir Usuario");
        MenuMasUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMasUserMouseClicked(evt);
            }
        });
        jMenu2.add(MenuMasUser);

        MenuMenosUser.setText("Eliminar Usuario");
        MenuMenosUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMenosUserMouseClicked(evt);
            }
        });
        jMenu2.add(MenuMenosUser);

        jMenuBar1.add(jMenu2);

        MVenProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Venta2.png"))); // NOI18N
        MVenProd.setText("Ventas de Productos   ");
        MVenProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MVenProdMouseClicked(evt);
            }
        });
        jMenuBar1.add(MVenProd);

        MSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        MSalir.setText("Salir");
        MSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(MSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MSalirMouseClicked

    private void MVenProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MVenProdMouseClicked
        VenPro VentanaVenPro= new VenPro();
        VentanaVenPro.setVisible(true);
        VentanaVenPro.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MVenProdMouseClicked

    private void MRegProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MRegProdMouseClicked
        RegPro VentanaRegPro= new RegPro();
        VentanaRegPro.setVisible(true);
        VentanaRegPro.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MRegProdMouseClicked

    private void MActInvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MActInvMouseClicked
        ActInv VentanaActInv= new ActInv();
        VentanaActInv.setVisible(true);
        VentanaActInv.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MActInvMouseClicked

    private void MenuMasUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMasUserMouseClicked
        MasUser VentanaMasUser= new MasUser();
        VentanaMasUser.setVisible(true);
        VentanaMasUser.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MenuMasUserMouseClicked

    private void MenuMenosUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMenosUserMouseClicked
        MenosUser VentanaMenosUser= new MenosUser();
        VentanaMenosUser.setVisible(true);
        VentanaMenosUser.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MenuMenosUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuExa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuExa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuExa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuExa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuExa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MActInv;
    private javax.swing.JMenu MRegProd;
    private javax.swing.JMenu MSalir;
    private javax.swing.JMenu MVenProd;
    private javax.swing.JMenu MenuMasUser;
    private javax.swing.JMenu MenuMenosUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
