/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author marij
 */
public class RegPro extends javax.swing.JFrame {

    /**
     * Creates new form RegPro
     */
    public RegPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LbMarcaPro = new javax.swing.JLabel();
        LbNomPro = new javax.swing.JLabel();
        LbPresProd = new javax.swing.JLabel();
        LbPrecio = new javax.swing.JLabel();
        BtnOk = new javax.swing.JButton();
        TfPrecio = new javax.swing.JTextField();
        TfNombre = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        TfPresProd = new javax.swing.JTextField();
        LbFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mregresa = new javax.swing.JMenu();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbMarcaPro.setText("Marca del producto:");
        getContentPane().add(LbMarcaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        LbNomPro.setText("Nombre del producto:");
        getContentPane().add(LbNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        LbPresProd.setText("Presentacion del producto:");
        getContentPane().add(LbPresProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        LbPrecio.setText("Precio del producto:");
        getContentPane().add(LbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        BtnOk.setText("Aceptar");
        BtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));
        getContentPane().add(TfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 410, -1));

        TfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(TfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 410, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 410, -1));
        getContentPane().add(TfPresProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 410, -1));

        LbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        LbFondo.setText("jLabel1");
        getContentPane().add(LbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 340));

        Mregresa.setText("Regresar");
        Mregresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MregresaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mregresa);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MregresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MregresaMouseClicked
        MenuExa ventanaMenu= new MenuExa();
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MregresaMouseClicked

    private void TfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNombreActionPerformed

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk;
    private javax.swing.JLabel LbFondo;
    private javax.swing.JLabel LbMarcaPro;
    private javax.swing.JLabel LbNomPro;
    private javax.swing.JLabel LbPrecio;
    private javax.swing.JLabel LbPresProd;
    private javax.swing.JMenu Mregresa;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JTextField TfPrecio;
    private javax.swing.JTextField TfPresProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
