/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import com.devazt.networking.HttpClient;
import com.devazt.networking.OnHttpRequestComplete;
import com.devazt.networking.Response;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;
/**
 *
 * @author marij
 */
public class RegPro extends javax.swing.JFrame {

    int estado;
    
    public RegPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LbMarcaPro = new javax.swing.JLabel();
        LbNomPro = new javax.swing.JLabel();
        LbPresProd = new javax.swing.JLabel();
        LbPrecio = new javax.swing.JLabel();
        BtnOk = new javax.swing.JButton();
        TfPrecio = new javax.swing.JTextField();
        TfNomPro = new javax.swing.JTextField();
        TfMarcaPro = new javax.swing.JTextField();
        TfPresProd = new javax.swing.JTextField();
        LbIdProd = new javax.swing.JLabel();
        TfIdProd = new javax.swing.JTextField();
        LbFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mregresa = new javax.swing.JMenu();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbMarcaPro.setText("Marca del producto:");
        getContentPane().add(LbMarcaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        LbNomPro.setText("Nombre del producto:");
        getContentPane().add(LbNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        LbPresProd.setText("Presentacion del producto:");
        getContentPane().add(LbPresProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        LbPrecio.setText("Precio del producto:");
        getContentPane().add(LbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        BtnOk.setText("Aceptar");
        BtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));
        getContentPane().add(TfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 410, -1));

        TfNomPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNomProActionPerformed(evt);
            }
        });
        getContentPane().add(TfNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 410, -1));
        getContentPane().add(TfMarcaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 410, -1));
        getContentPane().add(TfPresProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 410, -1));

        LbIdProd.setText("Id del producto:");
        getContentPane().add(LbIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        TfIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfIdProdActionPerformed(evt);
            }
        });
        getContentPane().add(TfIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 410, -1));

        LbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        LbFondo.setText("jLabel1");
        getContentPane().add(LbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 340));

        Mregresa.setText("Regresar");
        Mregresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MregresaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mregresa);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MregresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MregresaMouseClicked
        MenuExa ventanaMenu= new MenuExa();
        ventanaMenu.estado=this.estado;
        if(estado == 1){
            ventanaMenu.nivel1();
        }
        else if (estado == 2){
            ventanaMenu.nivel2();
        }
        else if (estado ==3 ){
            ventanaMenu.nivel3();
        }
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MregresaMouseClicked

    private void TfNomProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNomProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNomProActionPerformed

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
       HttpClient cliente = new HttpClient(new OnHttpRequestComplete() {
            @Override
            public void onComplete(Response status) {
                
                if (status.isSuccess()) {
                    JOptionPane.showMessageDialog(null, "Se Registro correctamente  el producto en la Base de datos.");
                } else {
                    JOptionPane.showMessageDialog(null, "No se puede registrar el producto en la base de datos. ");
                }

                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
        
        String Id_Prod = TfIdProd.getText().toString();
        String Nombre = TfNomPro.getText().toString();
        String Marca = TfMarcaPro.getText().toString();
        String Presentacion = TfPresProd.getText().toString();
        String Precio = TfPrecio.getText().toString();

        cliente.excecute("http://localhost/Api/Exa_RegProd.php?Id_Prod=" + Id_Prod + "&Nombre="+Nombre+"&Marca="+Marca+"&Presentacion="+Presentacion+"&Precio="+Precio+"");
    }//GEN-LAST:event_BtnOkActionPerformed

    private void TfIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfIdProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfIdProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk;
    private javax.swing.JLabel LbFondo;
    private javax.swing.JLabel LbIdProd;
    private javax.swing.JLabel LbMarcaPro;
    private javax.swing.JLabel LbNomPro;
    private javax.swing.JLabel LbPrecio;
    private javax.swing.JLabel LbPresProd;
    private javax.swing.JMenu Mregresa;
    private javax.swing.JTextField TfIdProd;
    private javax.swing.JTextField TfMarcaPro;
    private javax.swing.JTextField TfNomPro;
    private javax.swing.JTextField TfPrecio;
    private javax.swing.JTextField TfPresProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
