/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author marij
 */
public class VenPro extends javax.swing.JFrame {

    /**
     * Creates new form VenPro
     */
    public VenPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        BtnOk = new javax.swing.JButton();
        LbAviso = new javax.swing.JLabel();
        TfIdProd = new javax.swing.JTextField();
        LbIdPro = new javax.swing.JLabel();
        TfNombre = new javax.swing.JTextField();
        LbNomPro1 = new javax.swing.JLabel();
        LbPresProd = new javax.swing.JLabel();
        TfPresProd = new javax.swing.JTextField();
        TfCant = new javax.swing.JTextField();
        LbCant = new javax.swing.JLabel();
        TfPrecTot = new javax.swing.JTextField();
        LbPrecTot = new javax.swing.JLabel();
        LbCant1 = new javax.swing.JLabel();
        TfCant1 = new javax.swing.JTextField();
        LbFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mregresar = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnOk.setText("Aceptar");
        BtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        LbAviso.setText("El producto no esta registrado.");
        getContentPane().add(LbAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        TfIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfIdProdActionPerformed(evt);
            }
        });
        getContentPane().add(TfIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 390, -1));

        LbIdPro.setText("Id del producto:");
        getContentPane().add(LbIdPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        TfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(TfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 400, -1));

        LbNomPro1.setText("Nombre del producto:");
        getContentPane().add(LbNomPro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        LbPresProd.setText("Presentacion del producto:");
        getContentPane().add(LbPresProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
        getContentPane().add(TfPresProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 400, -1));
        getContentPane().add(TfCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 250, -1));

        LbCant.setText("Cantidad a comprar:");
        getContentPane().add(LbCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        getContentPane().add(TfPrecTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 170, 20));

        LbPrecTot.setText("Total a pagar:");
        getContentPane().add(LbPrecTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 20));

        LbCant1.setText("Cantidad del producto:");
        getContentPane().add(LbCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        getContentPane().add(TfCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 400, -1));

        LbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.png"))); // NOI18N
        LbFondo.setText("jLabel1");
        getContentPane().add(LbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 330));

        Mregresar.setText("Regresar");
        Mregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MregresarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mregresar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MregresarMouseClicked
        MenuExa ventanaMenu= new MenuExa();
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MregresarMouseClicked

    private void TfIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfIdProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfIdProdActionPerformed

    private void TfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNombreActionPerformed

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk;
    private javax.swing.JLabel LbAviso;
    private javax.swing.JLabel LbCant;
    private javax.swing.JLabel LbCant1;
    private javax.swing.JLabel LbFondo;
    private javax.swing.JLabel LbIdPro;
    private javax.swing.JLabel LbNomPro1;
    private javax.swing.JLabel LbPrecTot;
    private javax.swing.JLabel LbPresProd;
    private javax.swing.JMenu Mregresar;
    private javax.swing.JTextField TfCant;
    private javax.swing.JTextField TfCant1;
    private javax.swing.JTextField TfIdProd;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JTextField TfPrecTot;
    private javax.swing.JTextField TfPresProd;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
